#!/usr/bin/env bash
# fetch_upstream.sh — fetch or verify pinned upstream checkouts under oss/.
#
# Policy (plans/2026-08-23-open-source-standards.md §3): upstream content is never
# committed to this repository. This script reproduces the local development state:
# - clones upstream repositories into oss/<name> when absent,
# - records the checked-out commit SHA of whatever is present,
# - verifies SHA-256 digests of the specific files agentic-music depends on,
# - regenerates docs/upstream.md from scratch on every run.
#
# Usage: scripts/fetch_upstream.sh [--update]
#   --update  fast-forward existing checkouts to their remote default branch.
#
# JSON contract (stdout):
#
#   fetch_upstream/v1
#   {
#     "schema": "fetch_upstream/v1",
#     "repos": [
#       {
#         "name": "minimax-music3",
#         "url": "...",
#         "commit": "<sha>|null",          // null when checkout lacks .git
#         "action": "cloned|verified|updated|present-no-git",
#         "digests": { "skills/music-caption-rewriter/SKILL.md": "<sha256>", ... },
#         "missing_required_files": []
#       }, ...
#     ],
#     "docs_written": "docs/upstream.md",
#     "ok": true
#   }

set -euo pipefail

UPDATE=0
[[ "${1:-}" == "--update" ]] && UPDATE=1

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OSS_DIR="$REPO_ROOT/oss"
DOCS_DIR="$REPO_ROOT/docs"
mkdir -p "$OSS_DIR" "$DOCS_DIR"

# name|git_url|default_ref|required files (space-separated)
UPSTREAMS=(
  "minimax-music3|https://github.com/MiniMax-AI/MiniMax-Music3.git|main|README.md skills/music-caption-rewriter/SKILL.md skills/music-caption-rewriter/references/genre-router.md"
  "skills|https://github.com/MiniMax-AI/skills.git|main|LICENSE skills/minimax-music-gen/SKILL.md skills/minimax-music-gen/references/prompt_guide.md"
)

sha256_of() { sha256sum "$1" | cut -d' ' -f1; }

emit_repo_json() {
  # prints one JSON object for a repo entry; uses globals NAME ACTION COMMIT DIGESTS MISSING
  printf '      {"name": "%s", "url": "%s", "commit": %s, "action": "%s", "digests": {%s}, "missing_required_files": [%s]}' \
    "$NAME" "$URL" "$COMMIT" "$ACTION" "$DIGESTS_JSON" "$MISSING_JSON"
}

RESULTS=()
ALL_OK=1

for entry in "${UPSTREAMS[@]}"; do
  IFS='|' read -r NAME URL REF FILES <<<"$entry"
  DIR="$OSS_DIR/$NAME"
  ACTION="verified"
  COMMIT="null"

  if [[ -d "$DIR/.git" ]]; then
    if [[ "$UPDATE" == "1" ]]; then
      git -C "$DIR" fetch --quiet origin "$REF" 2>/dev/null || true
      if git -C "$DIR" checkout --quiet "$REF" 2>/dev/null || git -C "$DIR" checkout --quiet FETCH_HEAD 2>/dev/null; then
        git -C "$DIR" pull --quiet --ff-only 2>/dev/null || true
        ACTION="updated"
      fi
    fi
    COMMIT="\"$(git -C "$DIR" rev-parse HEAD)\""
  elif [[ ! -d "$DIR" ]]; then
    echo "[fetch_upstream] cloning $URL -> oss/$NAME" >&2
    if git clone --quiet --depth 1 --branch "$REF" "$URL" "$DIR" 2>/dev/null || git clone --quiet "$URL" "$DIR"; then
      ACTION="cloned"
      COMMIT="\"$(git -C "$DIR" rev-parse HEAD)\""
    else
      echo "[fetch_upstream] WARNING: clone failed for $URL (offline?)" >&2
      ACTION="clone-failed"
      ALL_OK=0
    fi
  else
    ACTION="present-no-git"
  fi

  DIGESTS_JSON=""
  MISSING=()
  for rel in $FILES; do
    fpath="$DIR/$rel"
    if [[ -f "$fpath" ]]; then
      d="$(sha256_of "$fpath")"
      [[ -n "$DIGESTS_JSON" ]] && DIGESTS_JSON+=", "
      DIGESTS_JSON+="\"$rel\": \"$d\""
    else
      MISSING+=("\"$rel\"")
      ALL_OK=0
    fi
  done
  MISSING_JSON="${MISSING[*]:-}"
  MISSING_JSON="$(IFS=, ; echo "${MISSING[*]}")"

  RESULT="$(emit_repo_json)"
  RESULTS+=("$RESULT")
done

cat > "$DOCS_DIR/upstream.md" <<EOF
<!-- GENERATED by scripts/fetch_upstream.sh — do not edit by hand. Rerun the script. -->
# Upstream Pins

Policy: see plans/2026-08-23-open-source-standards.md §3. Upstream content is fetched
locally and git-excluded; this file records what state our work was verified against.

| Repo | URL | Pinned commit | Pinned date | Digests verified |
|------|-----|---------------|-------------|------------------|
EOF
NOW="$(date -u +%Y-%m-%d)"
for r in "${RESULTS[@]}"; do
  NAME="$(printf '%s' "$r" | sed -E 's/.*"name": "([^"]+)".*/\1/')"
  URL="$(printf '%s' "$r" | sed -E 's/.*"url": "([^"]+)".*/\1/')"
  COMMIT="$(printf '%s' "$r" | grep -o '"commit": "[^"]*"' | sed -E 's/.*"([^"]*)"$/\1/' || true)"
  NDIG="$(printf '%s' "$r" | grep -oE '"[A-Za-z0-9/._-]*": "[0-9a-f]{64}"' | wc -l)"
  printf '| %s | %s | %s | %s | %s |\n' "$NAME" "$URL" "${COMMIT:-n/a}" "$NOW" "$NDIG file(s)" >> "$DOCS_DIR/upstream.md"
done
cat >> "$DOCS_DIR/upstream.md" <<'EOF'

## Why these pins

- `minimax-music3`: model card, serving instructions (SGLang-Omni), and the official
  `music-caption-rewriter` skill documentation referenced by skills/compose-brief.
- `skills`: MIT-licensed MiniMax agent-skills collection; `minimax-music-gen` interaction
  protocol adapted into `skills/compose-brief` (attribution in NOTICE).

Digest verification covers exactly the files agentic-music reads; full checkouts are not
redistributed. See AGENTS.md hard rules before touching `oss/`.
EOF

JOINED="$(IFS=,$'\n'; echo "${RESULTS[*]}")"
printf '{\n  "schema": "fetch_upstream/v1",\n  "repos": [\n%s\n],\n  "docs_written": "docs/upstream.md",\n  "ok": %s\n}\n' \
  "$JOINED" "$([[ $ALL_OK == 1 ]] && echo true || echo false)"
